#!/usr/bin/env python3
"""Доводка сгенерированного quicktype Go-файла: снятие конверта, шапка, gofmt.

Конверт (корневой struct со свойством на каждую схему) — строительные леса
генератора, а не часть API: без него quicktype не именует схемы и схлопывает
oneOf-варианты, см. scripts/openapi_to_jsonschema.py, п. 5. В выдачу он
попадать не должен — это 119 полей, которых нет ни в одном ответе MAX.
Удаляется здесь, а не в переходнике: до quicktype он необходим.

Шапка `Code generated ... DO NOT EDIT.` — канон Go (та же строка, что ищут
`go generate`, golangci-lint и ревью-боты, точный шаблон — в go/build).
quicktype её не ставит.

gofmt — тоже quicktype её не выдаёт: `gofmt -l` на сырой выдаче показывает
файл как неотформатированный (генератор выравнивает поля по всей структуре,
включая строки комментариев).
"""
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "gen" / "quicktype" / "models.go"

# Имя корневого типа-конверта: quicktype берёт его из `--top-level`.
ENVELOPE_TYPE = "MaxBotAPI"

HEADER = """// Code generated by quicktype from openapi.MaxBotApi.yaml. DO NOT EDIT.
//
// Структуры Max Bot API, порождённые из TypeSpec-контракта:
//   main.tsp → tsp compile → openapi.MaxBotApi.yaml
//     → scripts/openapi_to_jsonschema.py → gen/max.schema.json
//     → quicktype → этот файл.
//
// Правки вносятся в *.tsp, затем `make gen-quicktype` в maxapi/.
//
// Дискриминированные union'ы (Update, Attachment, Button, MarkupElement,
// ReplyButton) представлены плоскими структурами: поля всех вариантов
// собраны в одну, необязательны, а вариант определяется полем-дискриминатором
// (update_type или type). Разбор в конкретный вариант — задача потребителя;
// quicktype UnmarshalJSON с диспетчеризацией по дискриминатору не порождает.
"""


def main():
    if not MODELS.is_file():
        print(f"Нет {MODELS.relative_to(ROOT)} — сначала выполните: npm run gen:quicktype")
        sys.exit(2)

    text = MODELS.read_text(encoding="utf-8")

    envelope = re.compile(rf"^type {ENVELOPE_TYPE} struct \{{\n.*?^\}}\n\n?", re.MULTILINE | re.DOTALL)
    text, removed = envelope.subn("", text)
    if removed != 1:
        print(
            f"Ожидался ровно один конверт `type {ENVELOPE_TYPE} struct`, найдено {removed} — "
            f"проверьте --top-level в команде quicktype"
        )
        sys.exit(2)

    if f"{ENVELOPE_TYPE}" in text:
        print(f"После удаления конверта в файле остались упоминания {ENVELOPE_TYPE}")
        sys.exit(2)

    text = text.replace("package maxapi\n", HEADER + "\npackage maxapi\n", 1)
    MODELS.write_text(text, encoding="utf-8")

    gofmt = shutil.which("gofmt")
    if gofmt is None:
        print("gofmt не найден в PATH — файл записан без форматирования")
    else:
        subprocess.run([gofmt, "-w", str(MODELS)], check=True)

    final = MODELS.read_text(encoding="utf-8")
    structs = len(re.findall(r"^type \w+ struct", final, re.MULTILINE))
    enums = len(re.findall(r"^type \w+ string", final, re.MULTILINE))
    print(
        f"{MODELS.relative_to(ROOT)}: конверт снят, {structs} структур + {enums} enum-типов, "
        f"{len(final.splitlines())} строк"
    )


if __name__ == "__main__":
    main()
